### PR TITLE
Fix capitalization and spacing mistakes

### PR DESCRIPTION
**Pull request by QuickMythril**

### CODE REVIEW

**Comment by QuickMythril** [comment]
as discussed in https://github.com/Qortal/qortal-ui/pull/293

**Comment by QuickMythril** [comment]
something that still needs fixed:

a "search and replace" mistake across the entire en.json file:
the word "node" was replaced with "Node" but this also changed the entry names, which are meant to be lowercase, and instances of all caps, like NODE MANAGEMENT. (see lines 41, 188-190, 197, 212, 969.)

**Comment by QuickMythril** [comment]
Also removed the "Show / Hide Ticker" entry that is no longer being used, and adjusted the entry numbers accordingly.

**Comment by crowetic** [comment]
if you MUST remove the one unused section, you'll want to do it AFTER my final commit is merged, there are a few other modifications.

**Review by crowetic — CHANGES_REQUESTED** [review]
If removing the single unused item is that important, please make a new request based on my most recent PR.

**Pull request closed without merging**
