### PR TITLE
update all languages with missing new group functions - corrections from late night mistakes - further us.json updates

### PR DESCRIPTION
**Pull request by crowetic**

### CODE REVIEW

**Comment by crowetic** [comment]
fixed some mistakes from yesterday's late night pull request, added new group functions, and updated all languages. There are still some further changes in US that do not exist in others, but mostly formatting. So will leave those alone for now. May change 'link' re-wording in another request.

**Comment by QuickMythril** [comment]
something that still needs fixed:

a "search and replace" mistake across the entire `en.json` file:
the word "node" was replaced with "Node" but this also changed the entry names, which are meant to be lowercase, and instances of all caps, like NODE MANAGEMENT.  (see lines 41, 188-190, 197, 212, 969, etc.)

here is a pull request containing the fixes:
https://github.com/crowetic/qortal-ui/pull/1

**Comment by QuickMythril** [comment]
Also what is the reason for randomly making some words capitalized?  That doesn't appear to improve anything, but looks more like arbitrary changes.  The changes should be applied to all languages equally, not for English only.  That doesn't really make any sense, and just creates extra work later for others.  Additionally, there are more appropriate ways to emphasize words using text formatting, instead of all caps.  (Edit:  Because for some languages, like Korean or Chinese, there is no capital, so another method is needed, which could just be used for all languages.)

**Comment by QuickMythril** [comment]
Lastly, if there is new text being added, then the pages that would show this text should be updated as well.  It seems like the new group function text entries are currently unused, making this pull request incomplete, and again making more work for others later.

**Comment by crowetic** [comment]
definitely not arbitrary changes, it was changed to make things easier for people to see, and easier for them to understand. I want to see what people think about it, and the only way to really do that is to push it and see what they say. 

The capitalization of Node is done on purpose as well, if you see a few that you think should be lowercase, then make the changes in a new request.

**Pull request merged**
