### PR TITLE
Add Hebrew translations

### PR DESCRIPTION
**Pull request by QuickMythril**

### CODE REVIEW

**Comment by AlphaX-Projects** [comment]
Isnt hebrew readed from right to left ? We dont have this in our ui to switch to this mode.

**Comment by QuickMythril** [comment]
when using Hebrew it displays Right-to-Left as part of the text itself.  i've tested and this is working in the UI without any additional changes.

other optimizations and changes can improve the Right-to-Left text experience, like moving menus to the other side of the screen, but this is not needed.  there is someone in the community who has offered to help work on that implementation.

**Comment by QuickMythril** [comment]
The last commit adds the new text entries from the following updates, matching the current translations on the master branch.

- Max password text changed from 8 to 5:
https://github.com/Qortal/qortal-ui/commit/907dd635ba41cb6fed39061f28092d71b8705018

- Text added for the Tour functions:
https://github.com/Qortal/qortal-ui/commit/454e0c0e92fd6c5a28afc9c5b4b67ab3befb02ad

- Text added for Start Node function:
https://github.com/Qortal/qortal-ui/commit/6123f5eb36794bcb344361ca9f1a5ff26cda40b6

**Comment by QuickMythril** [comment]
The last commit adds the new text entry from the following update, matching the current translations on the master branch.

- Text added for Bootstrap dialog:
https://github.com/Qortal/qortal-ui/commit/1019896cf4015cf4e02e5485d109125fe012b4b7

**Comment by QuickMythril** [comment]
The last commit adds the new text entries from the following update, matching the current translations on the master branch.

- Text added for LTC Wallet Repair:
https://github.com/Qortal/qortal-ui/commit/d6a34323abff3fb7efdbdf109fca32ed9c9951fd

**Comment by QuickMythril** [comment]
The last commit removes the text entry from the following update, matching the current translations on the master branch.

- Text removed for old unused code:
https://github.com/Qortal/qortal-ui/commit/abe344016cbafddf173bf7190371c3bae86d90d0

**Comment by QuickMythril** [comment]
Requested build of Qortal UI with Hebrew support, for testing on Hebrew language OS.

AppImage: https://drive.proton.me/urls/DVZP0K9N98#50hvpgwlQa14
exe: https://drive.proton.me/urls/81VD8XVMRM#dOr26ddh5eUm

**Comment by QuickMythril** [comment]
This has been tested on Hebrew OS and is properly readable as expected.  Reversing some of the UI elements is not necessary and can be added later optionally.  Please merge this pull request, as it is ready to be implemented.  There is a different translation being prepared as well, and merging this first will help avoid code conflicts.

**Comment by QuickMythril** [comment]
Replaced by https://github.com/Qortal/qortal-ui/pull/252

**Pull request closed without merging**
