### PR TITLE
Consolidate wallet code

### PR DESCRIPTION
**Pull request by QuickMythril**

### CODE REVIEW

**Comment by QuickMythril** [comment]
Merge conflicts have been resolved.

**Review by crowetic — APPROVED** [review]
As long as @AlphaX-Projects agrees that the code looks good, I think this is a good change.

**Comment by QuickMythril** [comment]
you have asked me before why it matter whether code is approved now or later, and this is a perfect example of why it matters.  since AlphaX prioritized approving his own massive code changes with 1000s of lines to review, instead of checking the pending PRs first, now there are many merge conflicts.  that basically means i have to go line by line and compare my changes to his and adjust it all.  so i have to redo all my work because you made it wait.  that's why it matters.

**Comment by QuickMythril** [comment]
_"Yes , will merge it today, when the conflicts solved"_

@AlphaX-Projects - if you want to merge it, then resolve the conflicts yourself, since you created them.

**Pull request closed without merging**
